site_name: PHP-Cache Documentation
copyright: © 2015 PHP Cache Team
theme: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
          permalink: true
    - sane_lists
    - admonition